### ISSUE TITLE
Exec path not found

### ISSUE THREAD

**Issue by philsinatra** [HaaLeo/vscode-stylint#10]
| VS Code Version | vscode-stylint Version | Installed Stylint Version | OS |
| --------------- | ---------------------- | ------------------------- | -- |
| 1.41.1  && 1.42.0-insider | 0.1.3 | stylint@2.0.0 | macOS 10.15.2  |

# Description

Error message notification appears immediately upon opening a `.styl` file.

![Screen Shot 2019-12-27 at 10 12 35 AM](https://user-images.githubusercontent.com/1465808/71523228-1f169300-2896-11ea-83bf-80ff49602b92.png)

## Actual Behavior

Extension appears to be working despite the error message constantly popping up.

# Steps to Reproduce

1. Error message appears as soon as a `.styl` file is opened in the editor.

# Logs

<details><pre><code>

[Info  - 10:26:09 AM] Stylint server stopped.
[Info  - 10:26:10 AM] Stylint server is running.
[Info  - 10:26:10 AM] Stylint exec path set to /usr/local/lib/node_modules/stylint/bin/stylint
[Error - 10:26:11 AM] Stylint stack trace:
[Error - 10:26:11 AM] Error: /usr/local/lib/node_modules/stylint/src/core/read.js:32
			throw Error( 'Stylint Error: No such file or dir exists!' )
			^

Error: Stylint Error: No such file or dir exists!
    at F.<anonymous> (/usr/local/lib/node_modules/stylint/src/core/read.js:32:10)
    at FSReqCallback.oncomplete (fs.js:165:21)
    at ChildProcess.<anonymous> (/Users/philipsinatra/.vscode-insiders/extensions/haaleo.vscode-stylint-0.1.3/server/node_modules/sb-exec/lib/index.js:56:20)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
</code></pre></details>

# Settings
<details><pre><code>

None.
</code></pre></details>

**Comment by HaaLeo** [comment]
@philsinatra thanks for the issue report. Unfortunately I cannot reproduce this issue due to lack of a mac and I could not reproduce it on windows.

**Comment by philsinatra** [comment]
The issue seems to have resolved itself 😕. Error message no longer appears and the files seem to be linting properly.
