### ISSUE TITLE
Where is the status bar button?

### ISSUE THREAD

**Issue by GollyJer** [HaaLeo/vscode-stylint#11]
Hi, I'm trying to get your extension working but need help troubleshooting.
I have `stylint.alwaysShowStatus` enabled but I don't see any buttons.

Also, I have trace:server set to verbose but don't see Stylint in the OUTPUT list.

![image](https://user-images.githubusercontent.com/689204/71707077-d3d01900-2d9c-11ea-88c5-ca1fb217957d.png)

Thanks for any help!

**Comment by HaaLeo** [comment]
looks like the extension is not activated. It get's activated as soon as you open a `stylus` file. Then you should at least see the output channel.

**Comment by GollyJer** [comment]
Hey! Thanks for the reply.

I'm using stylint+prettier with styled-components inside typescript files.
Here's my `.stylelintrc`. It works great when used from the command-line.
```javascript
{
  "processors": ["stylelint-processor-styled-components"],
  "rules": {
    "prettier/prettier": true
  },
  "defaultSeverity": "warning",
  "extends": [
    "stylelint-config-recommended",
    "stylelint-prettier/recommended",
    "stylelint-config-styled-components"
  ]
}
```
Am I correct in assuming I won't be able to get linting to work with my setup?

**Comment by HaaLeo** [comment]
I think you ended up in the wrong repository. This extension adds support for [stylint](https://github.com/SimenB/stylint) to vscode. I think you are looking for the [vscode-stylelint](https://github.com/stylelint/vscode-stylelint) plugin instead.

**Comment by GollyJer** [comment]
I'm an idiot. 🤪
Thanks.
