### ISSUE TITLE
Local .stylintrc in project-root isn't used/detected

### ISSUE THREAD

**Issue by maranomynet** [HaaLeo/vscode-stylint#3]
I have a `.stylintrc` in my project root (next to my package.json) but vscode-stylint doesn't pick it up.
Instead vscode-stylint only looks in the VSCode workspace root.

I believe the expected behavior would be for vscode-stylint to resolve the .stylintrc file by traversing up the directory tree from each open `*.styl` file, all the way up to the file-system root folder.

**Comment by maranomynet** [comment]
Point being - my VSCode workspace setup doesn't necessarily map directly to the setup of my individual project folders.

I admit I haven't looked too closely at how ESLint does this, so...

**Comment by HaaLeo** [comment]
@maranomynet can you please add an example setup, including folder/project structure and your user settings, to reproduce this.

**Comment by maranomynet** [comment]
Create the project/file structure:

```
mkdir workspace-root
cd workspace-root
mkdir myproject
cd myproject
npm init --yes
echo '{ "brackets":"always", "colons":"always" }' > .stylintrc
mkdir src
echo "body {" > src/styles.styl
echo "    margin: 0" >> src/styles.styl
echo "}" >> src/styles.styl
cd ..
vscode .
```

VSCode should be open with `workspace-root` as its base folder, and your file structcure should look like so:

```
workspace-root/
    myproject/
        .stylintrc
        package.json
        src/
            styles.styl
```

and `styles.styl` should contain the three lines below and you'll see how vscode-stylint complains about brackets and colons.

```
body {
    margin: 0
}
```

Now move `myproject/.stylintrc` up one level into `workspace-root` 

```
mv myproject/.stylintrc .
```

and see how the stylint rules instantly kick in.

**Comment by maranomynet** [comment]
...also my `workspace-root` could contain `myproject2`, `myproject3`, etc. — each with different  `.stylintrc` config

**Comment by maranomynet** [comment]
The only User-Settings that I have that seem relevant to this is:

```
    "stylint.packageManager": "yarn",
```

**Comment by HaaLeo** [comment]
You can add the setting [`stylint.workingDirectories`](https://github.com/HaaLeo/vscode-stylint/#settings-options):
```JSON
{
    "stylint.workingDirectories": [
        {
            "directory": "./myproject",
            "changeProcessCWD": true
        }
    ]
}
```

Now the extension will switch to the specified directory and resolve to the desired `.stylintrc` file before the linter is executed.

**Comment by cyraid** [comment]
Should this not be the default behaviour? When sharing the code, you wouldn't want someone elses lint file checking the one that's in your repository. This aligns with other linting solutions does it not?

Edit: I mean when placing a .stylintrc file in alongside package.json.
Edit Edit: Okay nvm restarted visual studio code and now it's working. Sorry guys.
