### ISSUE TITLE
Crashes when too many errors

### ISSUE THREAD

**Issue by szhu** [HaaLeo/vscode-stylint#4]
When stylint reports a lot of errors, this extension appears to cut off the stylint's JSON output, resulting in invalid JSON and a fatal error.

Steps to reproduce:

1. Attempt to lint this file:

    <details>
    <pre>
    .main
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
        height 1
    </pre>

    </details>

2. This error appears:
  `Stylint: Unexpected end of JSON input. Please see the 'Stylint' output channel for details.`

**Comment by szhu** [comment]
I haven't looked into it a lot, but the underlying cause may be that the extension isn't waiting for stylint to finish running before reading its output buffer.

**Comment by HaaLeo** [comment]
@szhu I could not reproduce that behaviour with vscode 1.29.1 and stylint 1.5.9 installed globally via npm.
When I open the file, the extension lints it as expected. Maybe you can share your vscode settings and the `.stylintrc` file you are using. And please set `"stylint.trace.server": "verbose"` and add the log of the extension when it crashes.

**Comment by HaaLeo** [comment]
Closing the issue due to inactivity. If you still experience the issue feel free to reopen it and add more details about the error.
