### ISSUE TITLE
Could this extension support .vue file?

### ISSUE THREAD

**Issue by ibufu** [HaaLeo/vscode-stylint#6]

**Comment by HaaLeo** [comment]
You can enable the extension for `*.vue` files by adding a [file association](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language) to your settings.
```JSON
"files.associations": {
    "*.vue": "stylus"
}
```

However I do not know whether this setting influences the behaviour of other extensions that relate to `*.vue` files.

**Comment by groenroos** [comment]
I didn't find this to be a useful solution, as it seems to run Stylint on the entire `.vue` file, and not just the Stylus code inside the `<style>` tag. Additionally, this seems to have the side effect of subjecting the entire `.vue` file to Stylus code highlighting.
